=== MeharbanSingh/Markup-language/assign.dtd
<!ELEMENT results (personal_details)>
<!ELEMENT personal_details (student_details*)>
<!ELEMENT student_details (students)>
<!ELEMENT students (student_id,title,surname,preferred_name,given_name,gender,date-of-birth,email,student_image,notes_details,addresses,course_attempts)>
<!ELEMENT student_id (#PCDATA)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT surname (#PCDATA)>
<!ELEMENT preferred_name (#PCDATA)>
<!ELEMENT given_name (#PCDATA)>
<!ELEMENT gender (#PCDATA)>
<!ELEMENT date-of-birth (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT student_image (#PCDATA)>
<!ELEMENT notes_details (notes*)>
<!ELEMENT notes (note)>
<!ELEMENT note (#PCDATA)>
<!ELEMENT addresses (address_details)>
<!ELEMENT address_details (correspondence_address,home_address)>
<!ELEMENT correspondence_address (start_date,address_line_1,address_line_2,address_line_3,suburb,post_code,home_ph,work_ph,mobile_no,fax_no)>
<!ELEMENT start_date (#PCDATA)>
<!ELEMENT address_line_1 (#PCDATA)>
<!ELEMENT address_line_2 (#PCDATA)>
<!ELEMENT address_line_3 (#PCDATA)>
<!ELEMENT suburb (#PCDATA)>
<!ELEMENT post_code (#PCDATA)>
<!ELEMENT home_ph (#PCDATA)>
<!ELEMENT work_ph (#PCDATA)>
<!ELEMENT mobile_no (#PCDATA)>
<!ELEMENT fax_no (#PCDATA)>
<!ELEMENT  home_address (start_date,address_line_1,address_line_2,address_line_3,suburb,post_code,home_ph,work_ph,mobile_no,fax_no)>
<!ELEMENT course_attempts (course_details*)>
<!ELEMENT course_details (course,link)>
<!ELEMENT course (#PCDATA)>
<!ATTLIST course code CDATA #REQUIRED >
<!ATTLIST course title CDATA #REQUIRED >
<!ELEMENT link (#PCDATA)>

=== MeharbanSingh/Markup-language/Mass1.xml
<?xml version = "1.0"?>

 <?xml-stylesheet type = "text/xsl" href = "assignments_1.xslt"?> 

<!DOCTYPE personal_details SYSTEM "assign.dtd">



<personal_details>



<student_details>



<students>



<student_id>10317725</student_id>

<title>Ms</title>

<surname>Panday</surname>

<preferred_name>Alisha</preferred_name>

<given_name>Ali</given_name>

<gender>Female</gender>

<date-of-birth>19-02-1995</date-of-birth>

<email>its_aliza_here@yahoo.com</email>

<student_image>a.jpg</student_image>

<notes_details>

<notes>
<note>Advanced diploma of dance has been completed.</note>
</notes>
<notes>
<note>bachelor has  not completed</note>
</notes>

</notes_details>

<addresses>



<address_details>



<correspondence_address>



<start_date>4/4/2014</start_date>

<address_line_1>186 banksia street</address_line_1>

<address_line_2>Unit 7</address_line_2>

<address_line_3>WA</address_line_3>

<suburb>TuartHill</suburb>

<post_code>6060 </post_code>

<home_ph>92785642</home_ph>

<work_ph>92231581</work_ph>

<mobile_no>0450151398</mobile_no>

<fax_no>9277506</fax_no>

</correspondence_address>



<home_address>

<start_date>20/03/2008</start_date>

<address_line_1>1 martin Place</address_line_1>

<address_line_2>Barrigan Drive</address_line_2>

<address_line_3>NSW</address_line_3>

<suburb>Maddington</suburb>

<post_code>6090</post_code>

<home_ph>92953062</home_ph>

<work_ph>92989452</work_ph>

<mobile_no>0450151398</mobile_no>

<fax_no>92104614</fax_no>

</home_address>



</address_details>

</addresses>



<course_attempts>



<course_details>

<course code  = "C41" title = "Completed" ></course>

<link>http://www.ecu.edu.au/handbook/course?id=C41&amp;year=2017</link>

</course_details>



<course_details>

<course code = "C26" title = "Discontinue"> </course>

<link>http://www.ecu.edu.au/handbook/course?id=C26&amp;year=2017</link>

</course_details>



</course_attempts>

</students>

</student_details>





<student_details>



<students>



<student_id>10317736</student_id>

<title>Mr</title>

<surname>Sidhu</surname>

<preferred_name>Gurjant</preferred_name>

<given_name>Guri</given_name>

<gender>Male</gender>

<date-of-birth>18-11-1991</date-of-birth>

<email>guri001@gmail.com</email>

<student_image>b.jpeg</student_image>

<notes_details>

<notes>
<note>students have completed the course M28 in High Distinction.</note>
</notes>
<notes>
<note>students have completed the course Y28.</note>
</notes>

</notes_details>

<addresses>



<address_details>



<correspondence_address>



<start_date>01/01/2013</start_date>

<address_line_1>35-51 Mitchell Street</address_line_1>

<address_line_2>McMahons Point</address_line_2>

<address_line_3>WA</address_line_3>

<suburb>Kenwick</suburb>

<post_code>6005</post_code>

<home_ph>97974900</home_ph>

<work_ph>92234500</work_ph>

<mobile_no>0410355053</mobile_no>

<fax_no>92234604</fax_no>

</correspondence_address>



<home_address>

<start_date>18/05/2000</start_date>

<address_line_1>Level 4</address_line_1>

<address_line_2>369 Royal Parade</address_line_2>

<address_line_3>NSW</address_line_3>

<suburb>Parkville</suburb>

<post_code>3052</post_code>

<home_ph>92349511</home_ph>

<work_ph>92749500</work_ph>

<mobile_no>0410355053</mobile_no>

<fax_no>90032604</fax_no>

</home_address>



</address_details>

</addresses>



<course_attempts>



<course_details>

<course code  = "M28" title = "Completed" ></course>

<link>http://www.ecu.edu.au/handbook/course?id=M28&amp;year=2017</link>

</course_details>



<course_details>

<course code = "Y78" title = "Completed"> </course>

<link>http://www.ecu.edu.au/handbook/course?id=Y78&amp;year=2017</link>

</course_details>



</course_attempts>

</students>

</student_details>

<student_details>



<students>



<student_id>10326635</student_id>

<title>Mr</title>

<surname>Chaudhary</surname>

<preferred_name>Kelvin</preferred_name>

<given_name>kanha</given_name>

<gender>Male</gender>

<date-of-birth>01-01-1989</date-of-birth>

<email>kelvinchau@gmail.com</email>

<student_image>c.jpg</student_image>

<notes_details>

<notes>
<note>student have completed the course.</note>
</notes>
<notes>
<note>student have discontinued the course .</note>
</notes>
</notes_details>

<addresses>



<address_details>



<correspondence_address>



<start_date>4/03/2016</start_date>

<address_line_1>Level 9</address_line_1>

<address_line_2>231 Adelaide Tce</address_line_2>

<address_line_3>WA</address_line_3>

<suburb>Perth</suburb>

<post_code>6000</post_code>

<home_ph>92213020 </home_ph>

<work_ph>92023121</work_ph>

<mobile_no>0413706491</mobile_no>

<fax_no>95689781</fax_no>

</correspondence_address>



<home_address>

<start_date>26/06/2005</start_date>

<address_line_1>Level 1</address_line_1>

<address_line_2> Block Court</address_line_2>

<address_line_3> 288-290 Collins Street</address_line_3>

<suburb>Victoria</suburb>

<post_code>3000</post_code>

<home_ph>91258511</home_ph>

<work_ph>92479504</work_ph>

<mobile_no>0413706491</mobile_no>

<fax_no>91288453</fax_no>

</home_address>



</address_details>

</addresses>



<course_attempts>



<course_details>

<course code  = "K13" title = "Completed" ></course>

<link>http://www.ecu.edu.au/handbook/course?id=K13&amp;year=2017</link>

</course_details>



<course_details>

<course code = " K82" title = "Discontinued"> </course>

<link>http://www.ecu.edu.au/handbook/course?id=K82&amp;year=2017</link>

</course_details>



</course_attempts>

</students>

</student_details>

<student_details>



<students>



<student_id>10417727</student_id>

<title>Mr</title>

<surname>Waraich</surname>

<preferred_name>Meherban</preferred_name>

<given_name>Mehu</given_name>

<gender>Male</gender>

<date-of-birth>23-06-1994</date-of-birth>

<email>waraich007@gmail.com</email>

<student_image>e.jpg</student_image>

<notes_details>

<notes>
<note>student have completed the course.</note>
</notes>
<notes>
<note>student have completed the course .</note>
</notes>
</notes_details>

<addresses>



<address_details>



<correspondence_address>



<start_date>11/02/2015</start_date>

<address_line_1>270 Joondalup Drive</address_line_1>

<address_line_2>Bilding 20</address_line_2>

<address_line_3>WA</address_line_3>

<suburb>Joondalup</suburb>

<post_code>6027</post_code>

<home_ph> 93441833</home_ph>

<work_ph> 91431823</work_ph>

<mobile_no>0451837422</mobile_no>

<fax_no>96689881</fax_no>

</correspondence_address>



<home_address>

<start_date>27/03/2006</start_date>

<address_line_1>Level 4</address_line_1>

<address_line_2>90 King William Street</address_line_2>

<address_line_3>SA</address_line_3>

<suburb>Adelaide</suburb>

<post_code>5000</post_code>

<home_ph>94348501</home_ph>

<work_ph>91879514</work_ph>

<mobile_no>0408803141</mobile_no>

<fax_no>90081452</fax_no>

</home_address>



</address_details>

</addresses>



<course_attempts>



<course_details>

<course code  = "K13" title = "Completed" ></course>

<link>http://www.ecu.edu.au/handbook/course?id=K13&amp;year=2017</link>

</course_details>



<course_details>

<course code = " K82" title = "Discontinued"> </course>

<link>http://www.ecu.edu.au/handbook/course?id=K82&amp;year=2017</link>

</course_details>



</course_attempts>

</students>

</student_details>

<student_details>



<students>



<student_id>10354608</student_id>

<title>Mr</title>

<surname>Leonard</surname>

<preferred_name>Sammy</preferred_name>

<given_name>Sam</given_name>

<gender>Male</gender>

<date-of-birth>14-06-1993</date-of-birth>

<email>SammyCool347@yahoo.com</email>

<student_image>h.jpg</student_image>

<notes_details>

<notes>
<note>student have done level 3 Certificate .</note>
</notes>
<notes>
<note>student have completed the course .</note>
</notes>
</notes_details>

<addresses>



<address_details>



<correspondence_address>



<start_date>16/05/2015</start_date>

<address_line_1>270 morley Drive</address_line_1>

<address_line_2>cnr crimea st</address_line_2>

<address_line_3>WA</address_line_3>

<suburb>Morley</suburb>

<post_code>6027</post_code>

<home_ph>93561833</home_ph>

<work_ph>91221823</work_ph>

<mobile_no>0451837566</mobile_no>

<fax_no>94489881</fax_no>

</correspondence_address>



<home_address>

<start_date>30/01/2006</start_date>

<address_line_1>Level 7</address_line_1>

<address_line_2>90 Hay Street</address_line_2>

<address_line_3>West perth</address_line_3>

<suburb>Perth</suburb>

<post_code>6011</post_code>

<home_ph>94344567</home_ph>

<work_ph>91427514</work_ph>

<mobile_no>0408768141</mobile_no>

<fax_no>900814452</fax_no>

</home_address>



</address_details>

</addresses>



<course_attempts>



<course_details>

<course code  = "C61" title = "Completed" ></course>

<link>http://www.ecu.edu.au/handbook/course?id=C61&amp;year=2017</link>

</course_details>



<course_details>

<course code = " C45" title = "completed"> </course>

<link>http://www.ecu.edu.au/handbook/course?id=C45&amp;year=2017</link>

</course_details>



</course_attempts>

</students>

</student_details>

<student_details>



<students>



<student_id>10417727</student_id>

<title>Mr</title>

<surname>Sachdeva</surname>

<preferred_name>Rahul</preferred_name>

<given_name>Sachu</given_name>

<gender>Male</gender>

<date-of-birth>08-11-1989</date-of-birth>

<email>Rahul_Sachdeva@gmail.com</email>

<student_image>f.jpg</student_image>

<notes_details>

<notes>
<note>Studying double major.</note>
</notes>
<notes>
<note>student have good academic marks .</note>
</notes>
</notes_details>

<addresses>



<address_details>



<correspondence_address>



<start_date>18/02/2015</start_date>

<address_line_1>99 St George tce</address_line_1>

<address_line_2>Level 20</address_line_2>

<address_line_3>WA</address_line_3>

<suburb>Perth</suburb>

<post_code>6000</post_code>

<home_ph>92241833</home_ph>

<work_ph> 914356723</work_ph>

<mobile_no>0451864122</mobile_no>

<fax_no>966345674</fax_no>

</correspondence_address>



<home_address>
